### PR TITLE
Change for Construct class for PHP 8.1 compatibility

### PR DESCRIPTION
**Pull request by SilinMykola**
Hello! We tried to update our project for PHP 8.1 compatibility but had an error with your module. I made some changes to fix compatibility with PHP8.1.

### CODE REVIEW

**Comment by SilinMykola** [comment]
@fgrosse Hi! Could you help with this PR please? 
Thank you!

**Comment by andrewbess** [comment]
Hello @fgrosse 
The PHP 8.1 has been released.
Making a compatibility of our project with PHP 8.1 relates from your extension.
Could you please share your plans with releasing new version of your extension with us?
Thank you in advance.

**Comment by xmav** [comment]
@afk11 @fgrosse Could you help to proceed with this ?

**Comment by stefandanaita** [comment]
@fgrosse it would be nice to get this in whenever you have some time 🙏🏻 😄

**Comment by fgrosse** [comment]
Hey all, sorry it took a month to review but I finally took the time and the change looks fine.

**Comment by TimWolla** [comment]
@fgrosse Awesome, thank you!

**Comment by fgrosse** [comment]
It looks like a minor change to me so I suppose bumping to v2.3.1 is the right thing? However maybe someone can confirm since I haven't touched any PHP in a long time and might misunderstand the implications of this change.

**Comment by xmav** [comment]
Fantastic! Will you do release which those changes soon?

**Comment by fgrosse** [comment]
Alright then, I also just realized there is another PR #85 which looks related. Should we try to include this in that release as well?

**Pull request merged**
