### PR TITLE
Add PHP 8.0 and 8.1 to CI build matrix

### PR DESCRIPTION
**Pull request by fgrosse**

### CODE REVIEW

**Comment by TimWolla** [comment]
As a heads up: This requires the changes from #85. And those require a newer PHP minimum version. 

The best current practice for the PHP version constraint in composer.json is not using `>=`, but instead whitelisting each PHP version separately: `~7.2.0 || ~7.3.0 || ~7.4.0 || ~8.0.0 || ~8.1.0`.

**Comment by fgrosse** [comment]
Yes looks like I could use some help here and if you have the time I promise to be more responsive for the resulting PR this time :)

I am also currently playing with the idea of simply declaring a new major version and ending support for PHP 7.2 or older. Do you think this would be a good idea?

**Comment by TimWolla** [comment]
> Yes looks like I could use some help here and if you have the time I promise to be more responsive for the resulting PR this time :)

Sounds good to me. I'll handle that during regular working hours. I just chimed once I saw the notification about your comment to make sure the release went smoothly while you were online.

> I am also currently playing with the idea of simply declaring a new major version and ending support for PHP 7.2 or older. Do you think this would be a good idea?

I'd certainly drop PHP 7.0 and PHP 7.1. It's hard to support the whole range from 7.0 to 8.1. 

Supporting PHP 7.3, but not PHP 7.2 does not really make sense, because PHP 7.3 does not bring anything useful to the feature table.

I'd go to either PHP 7.2, PHP 7.4, or PHP 8.0. I'd go with PHP 7.2, unless you plan on making use of the new features immediately. The minimum version can always be increased further if the need arises.

**Comment by fgrosse** [comment]
The reason I thought I would stop supporting PHP 7.2 was that apparently PHPUnit stopped supporting it as well: https://phpunit.de/announcements/phpunit-9.html

> PHPUnit now requires PHP 7.3 (or newer)
> 
> Active support for PHP 7.2 ended on November 30, 2019. The only actively supported versions of PHP as of February 7, 2020 are PHP 7.3 and PHP 7.4.

Apart from that I don't really have a strong opinion as long as it makes maintenance easier for all of us.

**Pull request closed without merging**
